name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      - name: Build
        run: docker build -t ghcr.io/${{ secrets.CR_USERNAME }}/moph-api-proxy:latest .
      - name: Push
        run: docker image push ghcr.io/${{ secrets.CR_USERNAME }}/moph-api-proxy:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        env:
          CR_USERNAME: ${{ secrets.CR_USERNAME }}
          CR_PAT: ${{ secrets.CR_PAT }}
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          envs: CR_USERNAME,CR_PAT
          script: |
            echo "$CR_PAT" | docker login ghcr.io -u "$CR_USERNAME" --password-stdin
            cd docker-apps/moph-api-proxy
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d moph-api-proxy
